org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.java.home=/home/mainframe/android-studio/jbr
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

android.builtInKotlin=true
android.newDsl=true
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,LIBRARY_CONSTRAINTS_SHOULD_BE_DISABLED

